version: '3.8'

services:
  mi-web:
    image: ghcr.io/esteven2003/mi-web:latest
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        # HTTP
        - "traefik.http.routers.miweb.rule=Host(`miweb.byronrm.com`)"
        - "traefik.http.routers.miweb.entrypoints=http"

        # HTTPS redirect
        - "traefik.http.middlewares.miweb-https.redirectscheme.scheme=https"
        - "traefik.http.routers.miweb.middlewares=miweb-https"

        # HTTPS router
        - "traefik.http.routers.miweb-secure.rule=Host(`miweb.byronrm.com`)"
        - "traefik.http.routers.miweb-secure.entrypoints=https"
        - "traefik.http.routers.miweb-secure.tls=true"
        - "traefik.http.routers.miweb-secure.tls.certresolver=le"

        # SERVICE PORT (NGINX)
        - "traefik.http.services.miweb.loadbalancer.server.port=80"

        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true